### ISSUE TITLE
Export interfaces as well

### ISSUE THREAD

**Issue by mariomurrent-softwaresolutions** [OwnYourData/oydid#1]
https://github.com/OwnYourData/oydid/blob/ea905e3d639945f595a0b56c148885c90e8e61b4/oydid-js/src/oydid.ts#L6

In order to use the interfaces used in parameters they should also be exported.

**Comment by fabianekc** [comment]
fixed in commit https://github.com/OwnYourData/oydid/commit/3fa84b4a01d885b89335163771fbb09b50cc20c2
